name: Build and Publish Bytecode

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: windows-latest
            platform: win32
            arch: x64
          - os: macos-15
            platform: darwin
            arch: x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.15.0'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build bytecode
      env:
        PLATFORM: ${{ matrix.platform }}
        ARCH: ${{ matrix.arch }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        node ./tools/pack.js ./codes/clients/index.js
        
    - name: Publish to npm
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        cd node_modules/*/
        npm publish --access public
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bytecode-${{ matrix.platform }}-${{ matrix.arch }}
        path: node_modules/*/
        retention-days: 90
