name: Build and Publish Bytecode

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: x32
          - os: windows-latest
            platform: win32
            arch: x64
          - os: windows-latest
            platform: win32
            arch: x32
          - os: macos-15
            platform: darwin
            arch: x64
          - os: macos-15
            platform: darwin
            arch: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.15.0'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build bytecode
      env:
        PLATFORM: ${{ matrix.platform }}
        ARCH: ${{ matrix.arch }}
      run: |
        # 设置Node.js架构
        if [ "${{ matrix.arch }}" = "x32" ]; then
          export NODE_OPTIONS="--max-old-space-size=4096"
        fi
        node ./tools/pack.js ./codes/clients/index.js
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bytecode-${{ matrix.platform }}-${{ matrix.arch }}
        path: node_modules/*/*.bc
        retention-days: 90

  create-release:
    needs: build-and-publish
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Bytecode builds for multiple platforms:
          
          - Linux x64
          - Linux x32
          - Windows x64
          - Windows x32
          - macOS x64 (Intel)
          - macOS arm64 (Apple Silicon)
        draft: false
        prerelease: false
        
    - name: Upload Release Assets - Linux x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/bytecode-linux-x64/
        asset_name: linux-x64.bc
        asset_content_type: application/octet-stream
        
    - name: Upload Release Assets - Linux x32
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/bytecode-linux-x32/
        asset_name: linux-x32.bc
        asset_content_type: application/octet-stream
        
    - name: Upload Release Assets - Windows x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/bytecode-win32-x64/
        asset_name: win32-x64.bc
        asset_content_type: application/octet-stream
        
    - name: Upload Release Assets - Windows x32
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/bytecode-win32-x32/
        asset_name: win32-x32.bc
        asset_content_type: application/octet-stream
        
    - name: Upload Release Assets - macOS x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/bytecode-darwin-x64/
        asset_name: darwin-x64.bc
        asset_content_type: application/octet-stream
        
    - name: Upload Release Assets - macOS arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/bytecode-darwin-arm64/
        asset_name: darwin-arm64.bc
        asset_content_type: application/octet-stream
